# Default values for cloud-jamie.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repositslory: gcr.io/turnkey-charter-195519/cloud-jamie
  tag: v1
  pullPolicy: IfNotPresent
  recipient_number: "+18475626149"
  restartPolicy: OnFailure

nodeSelector: {}

tolerations: []

affinity: {}
